"""empty message

Revision ID: 6a20251f944a
Revises: 
Create Date: 2017-10-16 01:19:27.736975

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a20251f944a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('flat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flat',
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('edited', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_m2', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_m2_floors', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('locality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ownership', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('floor', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('floor_string', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('m2', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('m2_floors', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('m2_balcony', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('m2_cellar', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('garage', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('final_inspection_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('energy_rating', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('elevator', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seller', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attractive_offer', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('api_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'flat_pkey')
    )
    op.drop_table('stations')
    # ### end Alembic commands ###
