"""empty message

Revision ID: de1108c44ae9
Revises: 6a20251f944a
Create Date: 2017-10-19 23:37:34.055012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de1108c44ae9'
down_revision = '6a20251f944a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estate',
    sa.Column('title', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('edited', sa.DATE(), nullable=True),
    sa.Column('price', sa.NUMERIC(), nullable=True),
    sa.Column('price_m2', sa.NUMERIC(), nullable=True),
    sa.Column('price_m2_floors', sa.NUMERIC(), nullable=True),
    sa.Column('price_notes', sa.TEXT(), nullable=True),
    sa.Column('locality', sa.TEXT(), nullable=True),
    sa.Column('state', sa.TEXT(), nullable=True),
    sa.Column('ownership', sa.TEXT(), nullable=True),
    sa.Column('link', sa.TEXT(), nullable=True),
    sa.Column('floor', sa.SMALLINT(), nullable=True),
    sa.Column('floor_string', sa.TEXT(), nullable=True),
    sa.Column('m2', sa.NUMERIC(), nullable=True),
    sa.Column('m2_floors', sa.NUMERIC(), nullable=True),
    sa.Column('m2_balcony', sa.NUMERIC(), nullable=True),
    sa.Column('m2_cellar', sa.NUMERIC(), nullable=True),
    sa.Column('garage', sa.BOOLEAN(), nullable=True),
    sa.Column('final_inspection_year', sa.INTEGER(), nullable=True),
    sa.Column('energy_rating', sa.CHAR(), nullable=True),
    sa.Column('elevator', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('seller', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('attractive_offer', sa.BOOLEAN(), nullable=True),
    sa.Column('api_link', sa.TEXT(), nullable=True),
    sa.Column('json', sa.JSON(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=True),
    sa.Column('latitude', sa.NUMERIC(), nullable=True),
    sa.Column('longitude', sa.NUMERIC(), nullable=True),
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('source', sa.TEXT(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estate')
    # ### end Alembic commands ###
